export const allianzResponze = {
  originalXml: null,
  errors: {
    errors: [
      "714, Verificar el riesgo, auto no tiene continuidad y el vehículo no es nuevo",
    ],
  },
  termDate: "20230418",
  status: "B",
  effectiveDate: "20220418",
  quotationDate: "20220418",
  quotationNumber: "17131214",
  vehicleDetails: {
    type: "ML 500",
    version: "5806047",
    shieldingValue: 0.0,
    gasSystemValue: 0.0,
    insuredValue: 1.68e8,
    vehicleYear: 2015,
    accessoriesValue: 0.0,
    brand: "MERCEDES BENZ",
    discountPNR: 0.0,
    classVehicle: "C.Camioneta pasajeros",
    protectionDevice: "1",
    Class: "C.Camioneta pasajeros",
  },
  riskTypeDesc: "Liviano Particulares",
  packages: [
    {
      packageName: "Autos Esencial",
      packageId: 29,
      coverages: [
        {
          insuredValue: 4.0e9,
          coverageName: "Responsabilidad Civíl Extracontractual",
          deductible: 0.0,
          coverageId: 1,
        },
        {
          insuredValue: 1.0,
          coverageName: "Emergencias en Carretera",
          deductible: 0.0,
          coverageId: 18,
        },
      ],
      payments: [
        {
          premiumValue: 981306.0,
          paymentId: "ANUAL",
          premiumValueSuccess: 981306.0,
        },
        {
          premiumValue: 85014.33,
          paymentId: "MENSUAL",
          premiumValueSuccess: 85014.33,
        },
        {
          premiumValue: 510084.0,
          paymentId: "SEMESTRAL",
          premiumValueSuccess: 510084.0,
        },
        {
          premiumValue: 255042.0,
          paymentId: "TRIMESTRAL",
          premiumValueSuccess: 255042.0,
        },
      ],
    },
    {
      packageName: "Autos Esencial + Totales",
      packageId: 31,
      coverages: [
        {
          insuredValue: 4.0e9,
          coverageName: "Responsabilidad Civíl Extracontractual",
          deductible: 0.0,
          coverageId: 1,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Daños de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 2,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Hurto de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 4,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Temblor,Terremoto, Erupción Volcánica",
          deductible: 1000000.0,
          coverageId: 6,
        },
        {
          insuredValue: 1200000.0,
          coverageName: "Gastos de Movilización para el asegurado",
          deductible: 0.0,
          coverageId: 9,
        },
        {
          insuredValue: 1.0,
          coverageName: "Asistencia de Grúa",
          deductible: 0.0,
          coverageId: 15,
        },
        {
          insuredValue: 1.0,
          coverageName: "Emergencias en Carretera",
          deductible: 0.0,
          coverageId: 18,
        },
      ],
      payments: [
        {
          premiumValue: 6155947.0,
          paymentId: "ANUAL",
          premiumValueSuccess: 6155947.0,
        },
        {
          premiumValue: 533171.83,
          paymentId: "MENSUAL",
          premiumValueSuccess: 533171.83,
        },
        {
          premiumValue: 3199033.0,
          paymentId: "SEMESTRAL",
          premiumValueSuccess: 3199033.0,
        },
        {
          premiumValue: 1599516.5,
          paymentId: "TRIMESTRAL",
          premiumValueSuccess: 1599516.5,
        },
      ],
    },
    {
      packageName: "Autos Plus",
      packageId: 32,
      coverages: [
        {
          insuredValue: 4.0e9,
          coverageName: "Responsabilidad Civíl Extracontractual",
          deductible: 0.0,
          coverageId: 1,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Daños de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 2,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Daños de Menor Cuantía",
          deductible: 1000000.0,
          coverageId: 3,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Hurto de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 4,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Hurto de Menor Cuantía",
          deductible: 1000000.0,
          coverageId: 5,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Temblor,Terremoto, Erupción Volcánica",
          deductible: 1000000.0,
          coverageId: 6,
        },
        {
          insuredValue: 1.0,
          coverageName: "Vehículo de Reemplazo",
          deductible: 0.0,
          coverageId: 8,
        },
        {
          insuredValue: 1200000.0,
          coverageName: "Gastos de Movilización para el asegurado",
          deductible: 0.0,
          coverageId: 9,
        },
        {
          insuredValue: 5.0e7,
          coverageName: "Amparo de Accidentes Personales",
          deductible: 0.0,
          coverageId: 11,
        },
        {
          insuredValue: 1.0,
          coverageName: "Asistencia de Grúa",
          deductible: 0.0,
          coverageId: 15,
        },
        {
          insuredValue: 1.0,
          coverageName: "Conductor Elegido",
          deductible: 0.0,
          coverageId: 16,
        },
        {
          insuredValue: 1.0,
          coverageName: "Asistencias Plus",
          deductible: 0.0,
          coverageId: 17,
        },
        {
          insuredValue: 1.0,
          coverageName: "Emergencias en Carretera",
          deductible: 0.0,
          coverageId: 18,
        },
      ],
      payments: [
        {
          premiumValue: 1.0282059e7,
          paymentId: "ANUAL",
          premiumValueSuccess: 1.0282059e7,
        },
        {
          premiumValue: 890230.83,
          paymentId: "MENSUAL",
          premiumValueSuccess: 890230.83,
        },
        {
          premiumValue: 5341383.0,
          paymentId: "SEMESTRAL",
          premiumValueSuccess: 5341383.0,
        },
        {
          premiumValue: 2670691.5,
          paymentId: "TRIMESTRAL",
          premiumValueSuccess: 2670691.5,
        },
      ],
    },
    {
      packageName: "Autos Llave en Mano",
      packageId: 33,
      coverages: [
        {
          insuredValue: 4.0e9,
          coverageName: "Responsabilidad Civíl Extracontractual",
          deductible: 0.0,
          coverageId: 1,
        },
        {
          insuredValue: 2.459e8,
          coverageName: "Daños de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 2,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Daños de Menor Cuantía",
          deductible: 1000000.0,
          coverageId: 3,
        },
        {
          insuredValue: 2.459e8,
          coverageName: "Hurto de Mayor Cuantía",
          deductible: 0.0,
          coverageId: 4,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Hurto de Menor Cuantía",
          deductible: 1000000.0,
          coverageId: 5,
        },
        {
          insuredValue: 1.68e8,
          coverageName: "Temblor,Terremoto, Erupción Volcánica",
          deductible: 1000000.0,
          coverageId: 6,
        },
        {
          insuredValue: 1.0,
          coverageName: "Vehículo de Reemplazo",
          deductible: 0.0,
          coverageId: 8,
        },
        {
          insuredValue: 1200000.0,
          coverageName: "Gastos de Movilización para el asegurado",
          deductible: 0.0,
          coverageId: 9,
        },
        {
          insuredValue: 5.0e7,
          coverageName: "Amparo de Accidentes Personales",
          deductible: 0.0,
          coverageId: 11,
        },
        {
          insuredValue: 2.459e8,
          coverageName: "Llave en Mano",
          deductible: 0.0,
          coverageId: 14,
        },
        {
          insuredValue: 1.0,
          coverageName: "Asistencia de Grúa",
          deductible: 0.0,
          coverageId: 15,
        },
        {
          insuredValue: 1.0,
          coverageName: "Conductor Elegido",
          deductible: 0.0,
          coverageId: 16,
        },
        {
          insuredValue: 1.0,
          coverageName: "Asistencias Plus",
          deductible: 0.0,
          coverageId: 17,
        },
        {
          insuredValue: 1.0,
          coverageName: "Emergencias en Carretera",
          deductible: 0.0,
          coverageId: 18,
        },
      ],
      payments: [
        {
          premiumValue: 1.3661972e7,
          paymentId: "ANUAL",
          premiumValueSuccess: 1.3661972e7,
        },
        {
          premiumValue: 1183156.0,
          paymentId: "MENSUAL",
          premiumValueSuccess: 1183156.0,
        },
        {
          premiumValue: 7098938.0,
          paymentId: "SEMESTRAL",
          premiumValueSuccess: 7098938.0,
        },
        {
          premiumValue: 3549469.0,
          paymentId: "TRIMESTRAL",
          premiumValueSuccess: 3549469.0,
        },
      ],
    },
  ],
};
