
import * as Yup from "yup";

export const sarlaftInitialValues = {
    date: "",
    city: "",
    office: "",
    requestType: "",
    vinculationType: "",
    tie_1: "",
    tie_2: "",
    tie_3: "",

    fullname: "",
    firstLastName: "",
    secondLastName: "",
    documentType: "",
    document: "",
    expeditionDate: "",
    expeditionCity: "",
    birthdate: "",
    birthCity: "",
    nationality: "",
    secondNationality: "",
    email: "",
    address: "",
    department: "",
    city: "",
    phone: "",
    cellphone: "",
    mainActivity: "",
    sector: "",
    ciu: "",
    activityType: "",
    occupation: "",
    position: "",
    companyName: "",
    companyAddress: "",
    companyCity: "",
    companyDepartment: "",
    companyPhone: "",
    optionalActivity: "",
    companyCiu: "",
    productOrService: "",
    income: "",
    expenses: "",
    assets: "",
    passives: "",
    heritage: "",
    otherIncome: "",
    otherIncomeDesc: "",
    publicExposed: "",
    tiesPublicExposed: "",
    publicResources: "",
    otherCountyObligations: "",
    otherCountyObligationsDesc: "",

    sourceFunds: "",

    carryOutInternationalTransactions: "",
    currency: "",
    internationalFinancialProduct: "",
    internationalAccounts: "",
};

const schema = Yup.object().shape({
    issue_date: Yup.string().required(),
});